# Goal
#float32[] a
#float32[] b
#float32[] c
std_msgs/Float32MultiArray a
std_msgs/Float32MultiArray b

uint32 matarow
uint32 matbcol
uint32 matbrow
uint64 request_id
uint64 node_priority
---
# Response
#float32[] c
std_msgs/Float32MultiArray c
---
# Feedback
uint8 progress
